name: Release Rrweb
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
          registry-url: https://registry.npmjs.org
      - name: Install
        run: yarn
      - name: Build all
        run: yarn build:all
      - name: Confirm new version
        run: python3 compare.py
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: yarn lerna publish --no-private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
