name: Release Rrweb
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/rrweb
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
          registry-url: https://registry.npmjs.org
      - name: Install
        run: yarn install
      - name: Bundle Browser
        run: yarn bundle:browser
      - name: Bundle Highlight
        run: yarn bundle:highlight
      - name: Confirm new version
        run: python3 compare.py
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
